name = "SPEX"
uuid = "2e82ff62-c43d-46c9-80e5-5e53f77aadfb"
authors = ["Will Kimmerer <kimmerer@mit.edu> and contributors"]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"

[compat]
CBinding = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
